Friends_Album/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from Friends import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('login/', views.login_user, name='login_user'),
    path('create_user/', views.create_user, name='create_user'),
    path('logout/', views.logout_user, name='logout_user'),

    path('slam_home/', views.slam_home, name='slam_home'),
    path('slam_home/make_slam/', views.make_slam, name='make_slam'),
    path('slam_home/view_slam/', views.view_slam, name='view_slam'),
    path('slam_home/view_slam/view_friend/', views.view_friend, name='view_friend'),
    path('slam_home/view_slam/remove_friend/', views.remove_friend, name='remove_friend'),
    path('slam_home/view_slam/edit_friend/', views.edit_friend, name='edit_friend'),

    path('slam_home/search_friend/', views.search_friend, name='search_friend'),

    path('about_us/', views.about_us, name='about_us'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Friends/models.py
from django.contrib.auth.models import User
from django.db import models


class SlamBook(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    slam_no = models.AutoField(primary_key=True)
    my_name = models.CharField(max_length=250,default='')
    my_nickname = models.CharField(max_length=250,default='')
    my_address = models.CharField(max_length=250,default='')
    my_mobile_number = models.CharField(max_length=250,default='')
    my_email = models.EmailField(max_length=250,default='')
    my_birth_day = models.DateField()
    my_crushes = models.CharField(max_length=250,default='')
    my_happiest_moment = models.CharField(max_length=250,default='')
    my_favourite_dishes = models.CharField(max_length=250,default='')
    my_favourite_sports = models.CharField(max_length=250,default='')
    my_favourite_places = models.CharField(max_length=250,default='')
    my_favourite_actor = models.CharField(max_length=250,default='')
    my_favourite_actress = models.CharField(max_length=250,default='')
    my_favourite_song = models.CharField(max_length=250,default='')
    my_goal = models.CharField(max_length=250,default='')
    opinion_about_you = models.CharField(max_length=250,default='')
    created_date = models.DateTimeField(auto_now=True)
    my_profile = models.ImageField(upload_to='slam_images/', blank=True, null=True)

    def __str__(self):
        return self.my_name

Friends/forms.py
from django import forms
from django.contrib.auth.models import User

from Friends.models import SlamBook
from django.contrib.auth.forms import UserCreationForm


class SlamBookForm(forms.ModelForm):
    class Meta:
        model = SlamBook
        fields = '__all__'
            # ['my_name', 'my_nickname', 'my_address',
            #       'my_mobile_number', 'my_email', 'my_birth_day',
            #       'my_crushes', 'my_happiest_moment', 'my_favourite_dishes',
            #       'my_favourite_sports', 'my_favourite_places', 'my_favourite_actor',
            #       'my_favourite_actress', 'my_favourite_webiste', 'my_favourite_festival',
            #       'my_favourite_song', 'my_goal', 'opinion_about_you', 'my_profile']


class RegitrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Friends/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from Friends.forms import *
from django.contrib.auth.views import LoginView
from Friends_Album import settings


def homepage(request):
    return render(request, 'home.html')


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect('slam_home')
        else:
            messages.warning(request, 'Invalid Username or Password')
            redirect('login_user')
    return render(request, 'login.html')


def logout_user(request):
    logout(request)
    return redirect('home')


def slam_home(request):
    # request.session.set_expiry(20)
    return render(request, 'slam_home.html')


def create_user(request):
    form = RegitrationForm()
    if request.method == 'POST':
        form = RegitrationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.info(request, 'Account was created for '+user)
            return redirect('login_user')

    return render(request, 'sign_up.html',{"form": form})


def make_slam(request):
    form = SlamBookForm()
    if request.method == 'POST'or request.method == 'FILES':
        # user = request.POST.get('user')
        # print(user)
        # user = SlamBook.objects.get()
        form = SlamBookForm(request.POST, request.FILES, None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Slam Saved Successfully...!!')
            return redirect('make_slam')
        else:
            return render(request, 'make_slam.html', {'error':form.errors,'form':SlamBookForm(request.POST, request.FILES, None)})
    else:
        return render(request, 'make_slam.html', {"form": form})


def view_slam(request):
    user = request.user.id
    return render(request, 'view_slam.html', {"slams": SlamBook.objects.filter(user=user)})


def view_friend(request):
    slam_no = request.GET.get('slam_no')
    slam = SlamBook.objects.get(slam_no=slam_no)
    return render(request, 'view_friend.html',{"slams": slam})


def remove_friend(request):
    slam_no = request.GET.get('slam_no')
    SlamBook.objects.get(slam_no=slam_no).delete()
    messages.success(request, 'You Lost One Slam...!!')
    return redirect('view_slam')


def edit_friend(request):
    slam_no = request.GET.get('slam_no')
    items = SlamBook.objects.get(slam_no=slam_no)
    if request.method == "POST" or request.method == "FILES":
        form = SlamBookForm(request.POST, request.FILES, instance=items)
        if form.is_valid():
            form.save()
            return redirect('view_slam')
    else:
        form = SlamBookForm(instance=items)
        return render(request, 'edit_slam.html', {"form": form})


def search_friend(request):
    search = request.GET.get("search")
    slam = SlamBook.objects.filter(my_name__icontains=search)
    return render(request, 'search.html', {"search": slam, "name": search})


def about_us(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <style>
        .card{
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);

        }
        th{
            padding: 20px 0;
        }
        td{
            padding: 20px;
        }
        .about-us img{
            height: 20px;
        }
        td{
            padding-right: 50px;
        }
    </style>

    <br>
    <br>
        <div class="container">
    <div class="row">
        <div class="col">
            <div class="card mb-4 p-2" style="height: 60vh">
            <h3 class="bg-info text-center p-4 text-light">About Us</h3>
                <hr>
            <table class="p-4" align="center" style="margin: 30px auto">
                <tr>
                    <td><img src="{% static 'phone.png' %}" class="about-us" height="40" width="40"></td>
                    <th>+91 9876543210</th>
                </tr>
                <tr>
                    <td><img src="{% static 'mail.png' %}" class="about-us" height="40" width="40"></td>
                    <th>e-commerce@service.com</th>
                </tr>
                <tr>
                    <td><img src="{% static 'location.png' %}" class="about-us" height="40" width="40"></td>
                    <th>Hyderabad</th>
                </tr>
            </table>
{#                <marquee style="">Hello</marquee>#}
            </div>
        </div>
    </div>
    </div>

{#    <h1 class="display-4" style="text-align: center; color: orange;font-size: 35px">About Us</h1>#}
{#        <div style="text-align: center">#}
{#            <table align="center" style="font-size: 25px">#}
{#            <tr>#}
{#                <td>Reach Us at : rakeshshu001@gmail.com</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>Contact Us : +91 8919736316</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>Telangana Hyd-35</td>#}
{#            </tr>#}
{#            </table>#}
{#        </div>#}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@500&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <link rel="icon" href="{% static 'images/icon.ico' %}">

    <style>
        .jumbotron ul li a:hover .fa{
            transform: rotateY(360deg);
        }
        .nav-link{
            padding-left: 50px;
            border-radius: 50%;
            transition: 0.5s;
        }
    </style>
</head>
<body>
{#<h1 class="display-4" align="center" style="color: white;background: white!important; background-color: #0062cc; height: 80px"><img src="{% static 'images/LogoMakr-3jmtXC.png' %}" style="width: 10%">Friends Slam Book</h1>#}
{#<hr>#}
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="font-family: 'Baloo 2', cursive;font-size: 22px">
      <a class="nav-link active" href="{% url 'home' %}"><i class="fa fa-home" aria-hidden="true"> </i>&nbsp;&nbsp;Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login_user' %}">User Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'create_user' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about_us' %}">About Us</a>
          </li>
        </ul>
      </div>
    </nav>
    {% block body %}
    {% endblock %}

    {% include 'footer.html' %}
{#    <div class="">#}
{#        <div class="col-lg-4" style="padding-left: 40%">#}
{#            <ul style="display: flex;text-decoration: none;list-style: none;align-items: center">#}
{#                <li><a href=""><i class="fa fa-whatsapp" aria-hidden="true"></i></a> </li>#}
{#                <li><a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a> </li>#}
{#                <li><a href=""><i class="fa fa-google-plus" aria-hidden="true"></i></a> </li>#}
{#            </ul>#}
{#        </div>#}
{##}
{#        <table border="2" align="center" style="width: 75%; line-height: 38px">#}
{##}
{#            <tr>#}
{#                <td>#}
{#                    <ul>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                    </ul>#}
{#                </td>#}
{##}
{#                <td>#}
{#                    <ul>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                    </ul>#}
{#                </td>#}
{##}
{#                <td>#}
{#                    <ul>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                        <li><a href="">Link</a></li>#}
{#                    </ul>#}
{#                </td>#}
{#            </tr>#}
{#        </table>#}
{#    </div>#}
{#    <div class="footer pb-2">#}
{#        <p align="center">Copyright ©2020 All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i> by Rakesh Roy</p>#}
{#    </div>#}
{##}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/edit_slam.html
{% extends 'slam_base.html' %}
{% load static %}
{% block title %}
    Friends Slam Book Home Page
{% endblock %}
{% block body %}
    <br>
    {% for x in messages %}
        <h3 class="display-4" style="color: lawngreen; font-size: 30px; text-align: center">{{ x }}</h3>
    {% endfor %}
    <br>
    <div class="row" style="padding-left: 20%">
        <div class="col-md-7" style=" background-color: lightcyan">
            <div class="card card-body" style=" background-color: lightyellow">
                <h3 class="display-4" style="font-size: 35px; color: #0062cc" align="center">Update Info...!!</h3>
                <hr>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="hidden" name="user" required="" id="id_user" value="{{ request.user.id }}">
                    <table class="table-sm" align="center" style="color: #e0a800">
{#                            <td colspan="4" align="right"><input type="hidden" name="user" required="" id="id_user" value="{{ form.user }}"></td>#}

                        <tr>
                            <td align="right">{{ form.my_name.label }}</td>
                            <td>{{ form.my_name }}</td>
                            <td align="right">{{ form.my_nickname.label }}</td>
                            <td>{{ form.my_nickname }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_address.label }}</td>
                            <td>{{ form.my_address }}</td>
                            <td align="right">{{ form.my_mobile_number.label }}</td>
                            <td>{{ form.my_mobile_number }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_email.label }}</td>
                            <td>{{ form.my_email }}</td>
                            <td align="right">{{ form.my_birth_day.label }}</td>
                            <td>{{ form.my_birth_day }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_crushes.label }}</td>
                            <td>{{ form.my_crushes }}</td>
                            <td align="right">{{ form.my_happiest_moment.label }}</td>
                            <td>{{ form.my_happiest_moment }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_dishes.label }}</td>
                            <td>{{ form.my_favourite_dishes }}</td>
                            <td align="right">{{ form.my_favourite_sports.label }}</td>
                            <td>{{ form.my_favourite_sports }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_places.label }}</td>
                            <td>{{ form.my_favourite_places }}</td>
                            <td align="right">{{ form.my_favourite_actor.label }}</td>
                            <td>{{ form.my_favourite_actor }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_actress.label }}</td>
                            <td>{{ form.my_favourite_actress }}</td>
                            <td align="right">{{ form.my_favourite_song.label }}</td>
                            <td>{{ form.my_favourite_song }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_goal.label }}</td>
                            <td>{{ form.my_goal }}</td>
                            <td align="right">{{ form.opinion_about_you.label }}</td>
                            <td>{{ form.opinion_about_you }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_profile.label }}</td>
                            <td>{{ form.my_profile }}</td>
                            <td></td>
                            <td></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td align="center" colspan="2"><button type="submit" class="btn btn-outline-info btn-block">Save Slam</button></td>
                            <td></td>
                        </tr>
                    </table>

{#                    <table class="table-sm" align="center" style="color: #e0a800">#}
{#                        <tr>#}
{#                            <td align="right">{{ form }}</td>#}
{#                            <td align="center" colspan="2"><button type="submit" class="btn btn-outline-info btn-block">Update Slam</button></td>#}
{#                        </tr>#}
{#                    </table>#}
                </form>
            </div>
        </div>
    </div>
    <div class="row">

    </div>
{% endblock %}

templates/footer.html
    <hr>
    <style>
        .footer-ul{
        color: #E3E3E3;
        }
        .nav-item{
            list-style: none;
            text-decoration: none;
            padding-top: 10px;
        }
        .nav-item .navbar-link{
            text-decoration: none;
            font-size: 18px;
            color: white;
        }
    </style>
    <div class="bg-info">
        <div class="footer">
            <div class="row m-2">
                <div class="col-sm-3 mt-4">
                    <ul class="footer-ul">ABOUT
                        <li class="nav-item"><a class="navbar-link" href="#">Contact Us</a></li>
                        <li class="nav-item"><a class="navbar-link" href="{% url 'about_us' %}">About Us</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Careers</a></li>
                        <li class="nav-item"><a class="navbar-link" href="https://defence-blogs.herokuapp.com/Blogs/Home/" target="_blank">Blogs</a></li>
                        <li class="nav-item"><a class="navbar-link" href="https://defence-blogs.herokuapp.com/" target="_blank">Portfolio</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 mt-4">
                    <ul class="footer-ul">HELP
                        <li class="nav-item"><a class="navbar-link" href="#">FAQ</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Report Infringement</a></li>
                    </ul>
                </div>
                <div class="col-sm-2 mt-4">
                    <ul class="footer-ul">POLICY
                        <li class="nav-item"><a class="navbar-link" href="#">Return Policy</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Terms Of Use</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Security</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Privacy</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#">Sitemap</a></li>
                    </ul>
                </div>
                <div class="col-sm-2 mt-4">
                    <ul class="footer-ul">SOCIAL
                        <li class="nav-item"><a class="navbar-link" href="#" target="_blank">Facebook</a></li>
                        <li class="nav-item"><a class="navbar-link" href="https://github.com/Rakesh-roy" target="_blank">Git</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#" target="_blank">Twitter</a></li>
                        <li class="nav-item"><a class="navbar-link" href="#" target="_blank">YouTube</a></li>
                    </ul>
                </div>
                <div class="col-sm-2 mt-4">
                    <ul style="border-left: 2px lightgray solid" class="footer-ul">Mail Us:
                        <li class="nav-item">info@gmail.com Hyderabad, 500037, Telangana, India
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <div class="text-center pb-4" style="color: #E3E3E3">
                Copyright &copy; | 2020
            </div>
        </div>
    </div>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Friends Slam Book
{% endblock %}
{% block body %}
    <style type="text/css">
    .body{
        background-image: url("{% static 'images/slambook.jpg' %}");
        background-repeat: no-repeat;
        background-size: cover;
    }
    </style>
    <h3 class="display-4 body" align="center" style="padding-top: 10px; padding-bottom: 10%;font-family: 'Baloo 2', cursive;">
    <em><font style="font-size: 20px">“A <strong>friend</strong> is someone <br>who understands your past, <br>believes in your future, <br>and accepts you just the way you are.”</font><br></em>
        <br>
        Welcome To Slam Book...!!<br><br>
        <a href="{% url 'login_user' %}" class="btn btn-info btn-md">Utilize the Fasilities</a>
    </h3>
{% endblock %}

templates/make_slam.html
{% extends 'slam_base.html' %}
{% load static %}
{% block title %}
    Friends Slam Book Home Page
{% endblock %}
{% block body %}
    <br>
    {% for x in messages %}
        <h3 class="display-4" style="color: lawngreen; font-size: 30px; text-align: center">{{ x }}</h3>
    {% endfor %}
    <h1>{{ error }}</h1>
    <br>
    <div style="padding: 5px 100px">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body" style=" background-color: lightyellow">
                <h3 class="display-4" style="font-size: 35px; color: #0062cc" align="center">Personal Info...!!</h3>
                <a href="{% url 'view_slam' %}" class="btn btn-outline-primary btn-sm">View All Slams</a>

                <hr>
                <form action="{% url 'make_slam' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" required="" id="id_user" value="{{ request.user.id }}">
                    <table class="table-sm" align="center" style="color: #e0a800">
{#                            <td colspan="4" align="right"><input type="hidden" name="user" required="" id="id_user" value="{{ form.user }}"></td>#}

                        <tr>
                            <td align="right">{{ form.my_name.label }}</td>
                            <td>{{ form.my_name }}</td>
                            <td align="right">{{ form.my_nickname.label }}</td>
                            <td>{{ form.my_nickname }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_address.label }}</td>
                            <td>{{ form.my_address }}</td>
                            <td align="right">{{ form.my_mobile_number.label }}</td>
                            <td>{{ form.my_mobile_number }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_email.label }}</td>
                            <td>{{ form.my_email }}</td>
                            <td align="right">{{ form.my_birth_day.label }}</td>
                            <td>{{ form.my_birth_day }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_crushes.label }}</td>
                            <td>{{ form.my_crushes }}</td>
                            <td align="right">{{ form.my_happiest_moment.label }}</td>
                            <td>{{ form.my_happiest_moment }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_dishes.label }}</td>
                            <td>{{ form.my_favourite_dishes }}</td>
                            <td align="right">{{ form.my_favourite_sports.label }}</td>
                            <td>{{ form.my_favourite_sports }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_places.label }}</td>
                            <td>{{ form.my_favourite_places }}</td>
                            <td align="right">{{ form.my_favourite_actor.label }}</td>
                            <td>{{ form.my_favourite_actor }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_favourite_actress.label }}</td>
                            <td>{{ form.my_favourite_actress }}</td>
                            <td align="right">{{ form.my_favourite_song.label }}</td>
                            <td>{{ form.my_favourite_song }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_goal.label }}</td>
                            <td>{{ form.my_goal }}</td>
                            <td align="right">{{ form.opinion_about_you.label }}</td>
                            <td>{{ form.opinion_about_you }}</td>
                        </tr>
                        <tr>
                            <td align="right">{{ form.my_profile.label }}</td>
                            <td>{{ form.my_profile }}</td>
                            <td></td>
                            <td></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td align="center" colspan="2"><button type="submit" class="btn btn-outline-info btn-block">Save Slam</button></td>
                            <td></td>
                        </tr>
                    </table>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/search.html
{% extends 'slam_base.html' %}
{% load static %}
{% block title %}
    Friends Slam Book Home Page
{% endblock %}
{% block body %}
    <br>
    <h3 style="font-size: 30px; color: #16181b; padding-left: 200px">Search Results :</h3>
    {% if search|length < 1 %}
        <div style="padding-left: 200px">
        <p>no search results</p>
        <p>Your search -  <strong>{{ name }}</strong> - did not match any documents.</p>
        Suggestions:
            <ul>
                <li>Make sure that all words are spelled correctly.</li>
                <li>Try different keywords.</li>
                <li>Try more general keywords.</li>
            </ul>
        </div>
    {% else %}
    <br>

    <div class="row" style="padding-left: 200px">
        <div class="col-md-10" style=" background-color: lightcyan">
            <div class="card card-body" style=" background-color: lightyellow">
                <table class="table" align="center">
                    <tr style="background-color: lightgray; color: #0062cc">
                        <th>Name</th>
                        <th>Nickname</th>
                        <th>Address</th>
                        <th>Mobile</th>
                        <th>Email</th>
                        <th>DoB</th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    {% for x in search %}
                    <tr style="color: #16181b">
                        <td>{{ x.my_name|capfirst }}</td>
                        <td>{{ x.my_nickname|capfirst }}</td>
                        <td>{{ x.my_address|capfirst }}</td>
                        <td>{{ x.my_mobile_number }}</td>
                        <td>{{ x.my_email }}</td>
                        <td>{{ x.my_birth_day }}</td>
                        <td><a href="{% url 'view_friend' %}?slam_no={{ x.slam_no }}" class="btn btn-outline-warning btn-sm">View</a> </td>
                        <td><a href="{% url 'edit_friend' %}?slam_no={{ x.slam_no }}" class="btn btn-outline-info btn-sm">Edit</a> </td>
                        <td><a href="{% url 'remove_friend' %}?slam_no={{ x.slam_no }}" class="btn btn-outline-danger btn-sm">Remove</a> </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/slam_home.html
{% extends 'slam_base.html' %}
{% load static %}
{% block title %}
    Friends Slam Book Home Page
{% endblock %}
{% block body %}
    <style type="text/css">
    .body{
        background-image: url("{% static 'images/slambook.jpg' %}");
        background-repeat: no-repeat;
        background-size: cover;
    }
    </style>
    <h3 class="display-4 body" align="center" style="padding-top: 10px; padding-bottom: 30%">
    <em>
        <font style="font-size: 20px">“A <strong>friend</strong> is someone <br>who understands your past, <br>believes in your future, <br>and accepts you just the way you are.”</font><br></em>
        <br>
        Welcome To Slam Book Home Page...!!<br>
        <a href="{% url 'make_slam' %}" class="btn btn-outline-danger btn-md">Start Adding Slams</a>
    </h3>
{% endblock %}